map_type: costmap
footprint: [[-0.48,-0.325],[-0.48,0.325], [0.38, 0.325],[0.41, 0], [0.38,-0.325]] #设置机器的在坐标系内所占用的面积
footprint_padding: 0.1

obstacle_layer:
  enabled: true
  obstacle_range: 2.5 #最大障碍物检测范围
  raytrace_range: 5.5 #检测自由空间的最大范围
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
#  point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: zed/point_cloud/cloud_registered, expected_update_rate: 0.2, marking: true, clearing: true, min_obstacle_height: 0.15, max_obstacle_height: 1.5}

inflation_layer:
  enabled: true
  inflation_radius: 0.5
