global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  width: 30.0
  height: 30.0
  static_map: true

  plugins:
#  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
#  - {name: grid_layer,   type: 'simple_layer_namespace::GridLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

#  grid_layer:
#    enabled: false
#    visual_walls:  [{start_x: 3.2,start_y: 1.0,end_x: 3.2,end_y: -1.0},{start_x: 5.0,start_y: 5.0,end_x: 6.0,end_y: 6.0}]


