scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.35
    upper_angle: 1.35

- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.1
    upper_threshold: .inf
    lower_replacement_value: -.inf
    upper_replacement_value: 29